/**
 * Generates the loading-screen wordmark assets from the Caveat font.
 *
 * RoughJS can sketch an SVG path but has no concept of text, so the wordmark
 * is converted to vector outlines here, once, at build time. This keeps
 * opentype.js a devDependency — it never ships in the runtime bundle.
 *
 * Outputs:
 *   - src/components/loading/wordmarkPath.ts  — glyph path data (written)
 *   - a rough SVG of the wordmark             — printed to stdout, pasted
 *     into index.html's #boot-screen so the static first paint is already
 *     hand-drawn (no crisp→rough swap when React's canvas takes over).
 *
 * Run:  node scripts/genWordmark.mjs > /tmp/boot-wordmark.svg
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import opentype from 'opentype.js';
import rough from 'roughjs';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Fontsource ships a *static* Caveat (per-weight) as WOFF, which opentype.js
// parses cleanly. (opentype.js mis-parses the variable Caveat[wght].ttf.)
const FONT_URL =
  'https://cdn.jsdelivr.net/npm/@fontsource/caveat/files/caveat-latin-400-normal.woff';
const TEXT = "Doug's Found Wood";
const SIZE = 100; // reference em size; the runtime scales this path
const INK = '#5c4f3f';
const SEED = 1337;

const buf = await fetch(FONT_URL).then((res) => {
  if (!res.ok) throw new Error(`font fetch failed: ${res.status}`);
  return res.arrayBuffer();
});

const font = opentype.parse(buf);
const path = font.getPath(TEXT, 0, 0, SIZE);

// Build the path string from getPath().commands directly — opentype.js v2's
// Path.toPathData() emits NaN coordinates.
const r = (n) => Number(n.toFixed(3));
let d = '';
let x1 = Infinity, y1 = Infinity, x2 = -Infinity, y2 = -Infinity;
const track = (x, y) => {
  if (x < x1) x1 = x;
  if (x > x2) x2 = x;
  if (y < y1) y1 = y;
  if (y > y2) y2 = y;
};

for (const c of path.commands) {
  if (c.type === 'M') {
    d += `M${r(c.x)} ${r(c.y)}`;
    track(c.x, c.y);
  } else if (c.type === 'L') {
    d += `L${r(c.x)} ${r(c.y)}`;
    track(c.x, c.y);
  } else if (c.type === 'C') {
    d += `C${r(c.x1)} ${r(c.y1)} ${r(c.x2)} ${r(c.y2)} ${r(c.x)} ${r(c.y)}`;
    track(c.x1, c.y1);
    track(c.x2, c.y2);
    track(c.x, c.y);
  } else if (c.type === 'Q') {
    d += `Q${r(c.x1)} ${r(c.y1)} ${r(c.x)} ${r(c.y)}`;
    track(c.x1, c.y1);
    track(c.x, c.y);
  } else if (c.type === 'Z') {
    d += 'Z';
  }
}

if (d.includes('NaN')) throw new Error('path contains NaN — aborting');

const bbox = { x1: r(x1), y1: r(y1), x2: r(x2), y2: r(y2) };

// Write the path data module.
const ts =
  '// Auto-generated by scripts/genWordmark.mjs — do not edit by hand.\n' +
  '// Glyph outlines for the loading-screen wordmark, baked at build time so\n' +
  '// opentype.js stays a devDependency and never ships in the runtime bundle.\n' +
  `export const WORDMARK = ${JSON.stringify({ text: TEXT, size: SIZE, bbox, d })} as const;\n`;
writeFileSync(
  join(__dirname, '..', 'src', 'components', 'loading', 'wordmarkPath.ts'),
  ts,
);

// Generate a rough SVG of the wordmark for index.html's boot screen.
const gen = rough.generator();
const drawable = gen.path(d, {
  fill: INK,
  fillStyle: 'solid',
  stroke: INK,
  strokeWidth: 1.4,
  roughness: 1.1,
  bowing: 0.6,
  seed: SEED,
});
// Round coordinates to 1 decimal — RoughJS emits full-precision floats,
// which roughly triples the path-data size for no visible benefit.
const round1 = (pd) => pd.replace(/-?\d+\.\d+/g, (m) => (+m).toFixed(1));
let inner = '';
for (const set of drawable.sets) {
  const pd = gen.opsToPath(set);
  if (!pd) continue;
  if (set.type === 'fillPath') {
    inner += `<path d="${round1(pd)}" fill="${INK}" stroke="none"/>`;
  } else if (set.type === 'path') {
    inner += `<path d="${round1(pd)}" fill="none" stroke="${INK}" stroke-width="1.4" stroke-linecap="round"/>`;
  }
}
const pad = 8;
const vb = `${r(bbox.x1 - pad)} ${r(bbox.y1 - pad)} ${r(bbox.x2 - bbox.x1 + pad * 2)} ${r(bbox.y2 - bbox.y1 + pad * 2)}`;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}" role="img" aria-label="${TEXT}">${inner}</svg>\n`;
writeFileSync(join(__dirname, '..', 'public', 'boot-wordmark.svg'), svg);
process.stdout.write(`wrote public/boot-wordmark.svg (${svg.length} bytes)\n`);
